name: Build
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: snickerbockers/submodules-init@v4
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python my_script.py
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "firmware/official/scrips/requirements.txt"
    - name: Runing FBT
      run: build.sh
